import { Inter, Poppins } from 'next/font/google';

import { ReactNode } from 'react';
import { ContextProvider } from '@/context/ContextApi';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Define the props type for the RootLayout component

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
 

      <div>
        <ContextProvider>
          <div>{children}</div>
        </ContextProvider>
      </div>

  );
}
